### ISSUE TITLE
Backend Account Management

### ISSUE THREAD

**Issue by kchanba** [carfreekeywest/map#1]
– Set up Carto Mapbox, and Hosting

**Comment by ebrelsford** [comment]
# Carto

1. Go to [the Carto sign up page](https://carto.com/signup/) and sign up for an account using the same email account as you use for the other accounts. You won't need to enter any billing information for now.
2. Skip the questions on the next page.
3. Send us the username and password.

# Mapbox

1. Go to [the Mapbox sign up page](https://www.mapbox.com/studio/signup/) and sign up for an account using the same email account as you use for the other accounts.
2. Send us the username and password.

# Digital Ocean

1. Go to [the Digital Ocean sign up page](https://cloud.digitalocean.com/registrations/new) and sign up for a new account using the same email account as you use for the other accounts.
2. Check your email for the confirmation email from Digital Ocean and click the link inside.
3. Enter billing information on the page that loads. This credit card will be charged $5 per month.
4. Send us the username and password.

**Comment by ebrelsford** [comment]
@kchanba [the above](https://github.com/carfreekeywest/site/issues/1#issuecomment-279756429) contains my instructions for creating the three accounts. The Digital Ocean one requires a credit card, so I assume they will want to do it themselves. Like I said, it will get charged $5 per month. As for Carto and Mapbox, we could create them. The only catch is if we exceed the free plans someone will have to enter billing info.

I'd usually have the client do each of these so they're ultimately responsible for billing, but let me know if you think it would be better to handle them differently.

**Comment by kchanba** [comment]
Thanks @ebrelsford! I'll forward this info to Chris and Jim and post credentials in the issue.

**Comment by ebrelsford** [comment]
Okay, don't post the password here though, it's public!

**Comment by kchanba** [comment]
Oh good point!

**Comment by kchanba** [comment]
Hey @ebrelsford! Here is account information from SFCS:
 
## **Carto**
Log-in: SFCS
Email: cedenoj@pbworld.com
 
## **Mapbox**
Log-in: SFCS
Email: cedenoj@pbworld.com
 
## **Digital Ocean**
Log-in: cedenoj@pbworld.com

**Comment by ebrelsford** [comment]
Thanks @kchanba! We really shouldn't share passwords here since it's public. I removed them but we should change them. Should I change them to something and give the new passwords back to you? Or should they change them? Whatever is easiest.

**Comment by kchanba** [comment]
Ah shoot I forgot it's public, sorry about that. Yea let's change them and
you can email them back to me. Thanks Eric!
