### ISSUE TITLE
Bus/Bike Overlap Clean Up

### ISSUE THREAD

**Issue by kchanba** [carfreekeywest/map#15]

**Comment by ebrelsford** [comment]
@kchanba what exactly are you looking for here? We would need to update the bus route data so that it fits whatever criteria we want, and the data (shapefile) seems pretty chaotic.

**Comment by kchanba** [comment]
Can we have bus routes hidden on default? I think that is a good solution to them covering the bike routes on first glance. I'd like to emphasize the RT feature vs actually showing the bus routes.
