### ISSUE TITLE
Style bus routes

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/map#18]
They're in Mapbox but not styled.

**Comment by kchanba** [comment]
Hey @ebrelsford, is there any way we can split the data for the bus routes into four separate layers for the lines so that I can style each? Excluding the Duval Loop. So car looking at this resource:
https://www.kwtransit.com/map

Thanks!

**Comment by ebrelsford** [comment]
@kchanba as with other layers in Mapbox, you can duplicate the existing layer and filter it. I did this and added the filtered layers to a Bus Routes group.

**Comment by kchanba** [comment]
@ebrelsford thanks for doing that and for the explanation. I see now how it's done and that I could have figured it out, still adjusting to Mapbox and appreciate the support :)

**Comment by ebrelsford** [comment]
Glad to help!
