### ISSUE TITLE
Higher-res image for current location indicator text

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/map#24]
This is the 1mile_bike_walk image, it should be PNG as before since SVG will not work.

**Comment by kchanba** [comment]
Let's try this one @ebrelsford 
![1mile_bike_walk_hi_res](https://user-images.githubusercontent.com/2378745/27190722-7524a5e0-51c3-11e7-82d3-e47c020e001d.png)

**Comment by kchanba** [comment]
![1mile_bike_walk-hi-res](https://user-images.githubusercontent.com/2378745/27190774-942917a0-51c3-11e7-8938-8e9ef9ecea59.png)
It's invisible against the white background :)

**Comment by ebrelsford** [comment]
Much better! :+1:
