### ISSUE TITLE
Higher res POI imags

### ISSUE THREAD

**Issue by kchanba** [carfreekeywest/map#36]
Noticed that a few of the POIs are looking blurry at this size – specifically the RT transit icons and the tropics cinema, some of the theaters.

**Comment by ebrelsford** [comment]
@kchanba I have made the POI icons larger. Apparently this has to be done by resizing them in an SVG editor (Inkscape worked fine) one-by-one. A little tedious but I think they look better.

**Comment by ebrelsford** [comment]
@kchanba for the real-time icons, can you send higher-res versions of them?

**Comment by kchanba** [comment]
@ebrelsford here is the RT icon as both the wifi symbol and bus together and hi res
![rt_icon_hi_res](https://user-images.githubusercontent.com/2378745/27600567-63bbdc80-5b3a-11e7-80e8-0911b0b49863.png)
