### ISSUE TITLE
Design for standalone map

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/map#6]

**Comment by kchanba** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/2378745/24773798/901cf28c-1ae4-11e7-9344-70cf05475bf8.jpg)
Sketches from meeting on 4/6

**Comment by kchanba** [comment]
@ebrelsford hey! Here's a rough mock of the four main navigation items/features we envisioned this afternoon. I chose to do mobile first design, hopefully it will be easier to work 'backwards' to desktop. Let me know your thoughts and if these make sense to you. I will create more detailed designs to start collaborating on in InVision once I'm back from vacation.

Thanks!
Kate
[cfkw_mobile_mock_v1.pdf](https://github.com/carfreekeywest/map/files/904040/cfkw_mobile_mock_v1.pdf)

**Comment by kchanba** [comment]
Hey @ebrelsford! I've updated the wireframes to include design for the real time bus location information. Would you mind giving your thoughts before I send over to Key West?

Thanks!
Kate
[cfkw_mobile_mock_v4.pdf](https://github.com/carfreekeywest/map/files/993984/cfkw_mobile_mock_v4.pdf)
