### ISSUE TITLE
Parking lot icon

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/map#9]

**Comment by kchanba** [comment]
@ebrelsford here is the Parking Lot icon as a PNG, would you prefer SVG? Or what would be the best format?
![parking_lot](https://cloud.githubusercontent.com/assets/2378745/24918420/5e4c7a98-1eae-11e7-8661-bd2a035d2730.png)

**Comment by ebrelsford** [comment]
Yeah if you could provide an SVG that would be better.
